name: glassdoor_service
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
    http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/patrick.png

flutter_native_splash:
  color: "#083D77"
  image: icons/linkedin.png
  android_gravity: center

flutter_launcher_icons:
  android: true
  image_path: icons/linkedin.png 
  adaptive_icon_background: "#083D77"
  adaptive_icon_foreground: icons/linkedin.png
